### ISSUE TITLE
Plugin should ignore markdown

### ISSUE THREAD

**Issue by Czekoloczek** [noahnightmare/ErrorLogger#1]
In the LA Log file (no underline):
![image](https://github.com/user-attachments/assets/fc86536d-3939-491c-bc6c-b383c29b78a7)

On Discord (underline):
![image](https://github.com/user-attachments/assets/8beace87-fe16-4f4e-a0ca-de1e7803a45e)

markdown can be ignored by using codeblocks (\```\_\_text that would be underline but it won't\_\_\```) and/or by using backslashes (```\_\_text that would be underline but it won't\_\_```)

note that when using codeblocks you should still add a backslash before "```" so it doesn't break the codeblock

**Comment by uncarve** [comment]
Fixed newest release 1.0.3

https://github.com/noahnightmare/ErrorLogger/releases/tag/1.0.3

Thanks for bringing this to my attention. LocalAdmin logs should now appear in code blocks. Normal errors ordinarily appear in code blocks, however for LA logs I forgot to add these.
